#!/bin/bash

mkdir /tmp/mysql-restore
cd /tmp/mysql-restore

echo -e "Start Restoring Databases"
echo -e "\nCheck MySQL status"
/etc/init.d/mysql  status

read -r -p "If MySQL is running press Y else N  [y/n] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]; then

#   ********************************************** DUMP DATABASES *****************************************************

databases=`mysql -BNe "SHOW DATABASES;" | grep -v -E 'information_schema|performance_schema|mysql'`

#echo -e "Start Dumping Databases\n"

for db in $databases; do
	if  [[ "$db" != _* ]] ; then
        echo "Dumping database: $db"
	mysqldump  --databases $db > $db.sql
    	if [ $? -ne 0 ]; then
		echo $(tput setaf 1)Error:$(tput setaf 7) mysqldump failed for database: $db;
		echo "Fetching latest database backup of $db";
		/var/cw/scripts/bash/duplicity_restore.sh --src $db -d --dst '/tmp/mysql-restore/'
		if [ $? -ne 0 ]; then
			echo $(tput setaf 1)Error:$(tput setaf 7) Failed to fetch backup of $db; 
        		exit 1
		else
			cp /tmp/mysql-restore/mysql/*.sql "/tmp/mysql-restore/$db.sql"
			rm -r /tmp/mysql-restore/mysql/
    		fi
	fi
fi
done

#   ******************************************************************************************************************
#   ********************************************** STOPPING SERVICES *************************************************
#   ******************************************************************************************************************

echo -e "\nStopping MySQL monitoring"
monit unmonitor mysql

echo -e "\nStopping MySQL"
/etc/init.d/mysql  stop

#   ********************************************** REMOVING DATABASES ************************************************

echo -e "\nRemoving ibdata files"
rm /var/lib/mysql/ib*
#ls /var/lib/mysql
echo -e "\nDropping databases"
#databases=`ls |   grep .sql  | cut -d'.' -f1`

for db in $databases; do
    if  [[ "$db" != _* ]] ; then
        echo "Deleting database: $db"
        rm -rf /var/lib/mysql/$db
    fi
done

#ls /var/lib/mysql

#   ********************************************** STARTING SERVICES *************************************************

cp /etc/mysql/conf.d/custom-manual.cnf /tmp/mysql-restore/custom-manual.cnf.bk
echo -n "[mysqld]" > /etc/mysql/conf.d/custom-manual.cnf

echo -e "\nStarting MySQL"
/etc/init.d/mysql  start

echo -e "\nStart Monitoring MySQL"
#/etc/init.d/monit  start
monit monitor mysql

#   ********************************************** CREATING DATABASES ************************************************

echo -e "\nCreating Application's Databases:"

for db in $databases; do
#    if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
        if [[ "$db" != _* ]] ; then
	echo "Creating database: $db"
        mysql -e "CREATE DATABASE $db;"
	fi
done

#   ********************************************** IMPORTING DATABASES ***********************************************

echo -e "\nStart Importing Databases"
for db in $databases; do
     	if [[ "$db" != _* ]] ; then
        	echo "Importing database: $db"
        	mysql $db < $db.sql
	fi
done
echo -e "\n$(tput setaf 2)Success: $(tput setaf 7)Database Restored Successfully"
else
	echo -e "\nOperation Cancelled"
fi
